### ISSUE TITLE
Matis configs use non portable irs file paths

### ISSUE THREAD

**Issue by ghost** [L3vi47h4N/Viper4Linux-Configs#10]
I need to update these. If anyone wants to PR before I get to it, feel free.

**Comment by noahbliss** [comment]
hey @Rush-er I saw you made this change. Looks like you're missing a `"` at the end, but if you could make that fix and send a pull request I'd happily accept it!

**Comment by noahbliss** [comment]
Resolved through https://github.com/noahbliss/Viper4Linux-Configs/pull/11
