### ISSUE TITLE
Dynamic System removed on purpose?

### ISSUE THREAD

**Issue by alexruedi** [L3vi47h4N/Viper4Linux-Configs#2]

**Comment by ghost** [comment]
Please elaborate.

**Comment by alexruedi** [comment]
In the shared library file there is (even blanktext)
PARAM_HPFX_DYNSYS_YCOEFFS
PARAM_HPFX_DYNSYS_SIDEGAIN
PARAM_HPFX_DYNSYS_XCOEFFS
PARAM_HPFX_DYNSYS_PROCESS_ENABLED
PARAM_HPFX_DYNSYS_BASSGAIN

Therefore I expect it to work when adding it properly to gstviperfx.c and in header. Just no idea what the values are... 

However, why is dynamic system missing?

**Comment by alexruedi** [comment]
I made it work again! Still no idea who removed that.

It required several modifications.. Let me know if you want the dynamic system functionality as well....

**Comment by ghost** [comment]
Yeah sure thing. As long as it doesn't impact existing functionality send
me over a PR!

**Comment by ghost** [comment]
I'll leave this issue open so the templates get updated if we merge this feature. We can discuss back on the Viper4Linux issue.

**Comment by ghost** [comment]
After some ups and downs, this is now an implemented feature.
